version: '3.9'

services:
  db:
    image: postgres:15
    container_name: pcshop_db
    environment:
      POSTGRES_DB: pcshop
      POSTGRES_USER: pcadmin
      POSTGRES_PASSWORD: pcpass
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  api:
    build: .
    container_name: pcshop_api
    depends_on:
      - db
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/pcshop
      SPRING_DATASOURCE_USERNAME: pcadmin
      SPRING_DATASOURCE_PASSWORD: pcpass

volumes:
  pgdata:
